### PR TITLE
Upgrading images to Debian 11

### PR DESCRIPTION
**Pull request by ros-kamach**
For now, all images are based on Debian buster (10) that has a few vulnerabilities and we've hit a problem that we can fix some of those vulnerabilities only by upgrading Debian bullseye (11).

### CODE REVIEW

**Review by cin — APPROVED** [review]
Thanks @ros-kamach! Assuming this passes tests, this should be GTG.

**Comment by tomashibm** [comment]
The base image upgrade upgraded also Varnish (`6.1.1`->`6.5.1`). The VCL used in tests doesn't compile for some reason now. I'll get back once I fix it.

**Comment by cin** [comment]
We may need to consider how users will handle an upgrade in this case (i.e. VCL syntax changes, etc). Obviously we don't want to release an operator upgrade that breaks people's clusters.

**Comment by tomashibm** [comment]
@ros-kamach please pull the latest changes from `main`. We fixed the issue that's happening here.

**Comment by ros-kamach** [comment]
@tomashibm thanks,  the latest changes have been merged to the PR branch.

**Pull request merged**
