### PR TITLE
chore: add podAnnotaions to varnish pods and fix yq

### PR DESCRIPTION
**Pull request by robgordon89**
Added podAnnotations, with tests; required for some Kubernetes features (Linkerd)

Fixed yq for v4 [here](https://mikefarah.gitbook.io/yq/upgrading-from-v3)

### CODE REVIEW

**Comment by cin** [comment]
Hey @robgordon89. Sorry for the delay. I'm approving this PR but I doubt this will get merged unfortunately as no one at IBM is actively maintaining this project any longer. I have a [fork](https://github.com/cin/varnish-operator) that can be used going forward, but I think this repo is going to get archived eventually.

**Comment by robgordon89** [comment]
@cin thanks for the update, I have moved this PR to your fork hope you don't mind, are you going to maintain this fork for the time being ?

**Comment by cin** [comment]
@robgordon89 your change has been released. https://github.com/cin/varnish-operator/releases/tag/0.37.0

**Comment by robgordon89** [comment]
nice thanks 👍

**Pull request closed without merging**
